{
  local_backend: true,
  backend:
    { name: 'git-gateway', repo: 'HusamMohammed/point-site-f', branch: 'main' },

  media_folder: 'content/assets',
  public_folder: '/assets',

  collections:
    [
      {
        name: 'home',
        label: 'الرئيسية',
        folder: 'content/data/home',
        media_folder: '',
        public_folder: '',
        extension: 'json',
        format: 'json',
        editor: { preview: false },
        fields:
          [
            { label: 'النص الرئيسي', name: 'mainText', required: true },
            { label: 'Main Text', name: 'englishText', required: true },
            {
              label: 'صور الخلفية',
              name: 'images',
              widget: 'list',
              required: true,
              field: { label: 'صورة', name: image, widget: 'image' },
            },
          ],
      },
      {
        name: 'about',
        label: 'عنا',
        folder: 'content/data/about',
        extension: 'json',
        format: 'json',
        editor: { preview: false },
        fields:
          [
            { label: 'العنوان', name: 'title', required: true },
            { label: 'النص التعريفي', name: 'description', required: true },
            { label: 'Title', name: 'title_en', required: true },
            { label: 'Description', name: 'description_en', required: true },
          ],
      },
      {
        name: 'services1',
        label: 'سلايدر الخدمات العلوي',
        label_singular: 'خدمة',
        identifier_field: 'name',
        media_folder: '',
        public_folder: '',
        folder: 'content/data/services1',
        extension: 'json',
        format: 'json',
        create: true,
        editor: { preview: false },
        fields:
          [
            { label: 'اسم الخدمة', name: 'name', required: true },
            { label: 'نص توصيفي', name: 'description', required: true },
            { label: 'Service Name', name: 'name_en', required: true },
            { label: 'Service Description', name: 'description_en', required: true },
            { label: 'صورة', name: 'image', widget: 'image', required: true },
          ],
      },
      {
        name: 'services2',
        label: 'سلايدر الخدمات السفلي',
        label_singular: 'خدمة',
        identifier_field: 'name',
        media_folder: '',
        public_folder: '',
        folder: 'content/data/services1',
        extension: 'json',
        format: 'json',
        create: true,
        editor: { preview: false },
        fields:
          [
            { label: 'اسم الخدمة', name: 'name', required: true },
            { label: 'نص توصيفي', name: 'description', required: true },
             { label: 'Service Name', name: 'name_en', required: true },
            { label: 'Service Description', name: 'description_en', required: true },
            { label: 'صورة', name: 'image', widget: 'image', required: true },
          ],
      },
      {
        name: 'projects',
        label: 'الأعمال',
        label_singular: 'عمل',
        media_folder: '',
        public_folder: '',
        folder: 'content/data/projects1',
        extension: 'json',
        format: 'json',
        create: true,
        editor: { preview: false },
        fields:
          [
            { label: 'اسم العمل', name: 'title', required: true },
            { label: 'صورة', name: 'image', widget: 'image', required: true },
            { label: 'نص توصيفي للعمل', name: 'description', required: true },
            {
              label: '؟هل يوجد رابط',
              name: 'isLink',
              widget: 'boolean',
              default: false,
            },
            { label: 'لينك', name: 'url', widget: 'string', required: false },
            { label: 'Title', name: 'title_en', required: true },
            { label: 'Description', name: 'description_en', required: true },
          ],
      },
      {
        name: 'clients',
        label: 'عملاؤنا',
        label_singular: 'عميل',
        identifier_field: 'name',
        media_folder: '',
        public_folder: '',
        folder: 'content/data/clients',
        extension: 'json',
        format: 'json',
        create: true,
        editor: { preview: false },
        fields:
          [
            { label: 'الاسم', name: 'name', required: true },
            { label: 'الصورة', name: 'image', widget: 'image', required: true },
          ],
      },
      {
        name: 'contact',
        label: 'مغلومات التواصل',
        folder: 'content/data/contact',
        extension: 'json',
        format: 'json',
        editor: { preview: false },
        fields:
          [
            {
              label: '',
              name: 'title',
              widget: 'string',
              default: 'معلومات الاتصال',
            },
            {
              label: 'رقم  الهاتف',
              name: 'phone',
              widget: 'string',
              required: true,
            },
            { label: 'البريد الالكتروني', name: 'email', required: true },
            { label: 'الموقع', name: 'location', required: true },
            { label: 'عنصر تواصل اضافي', name: 'item4', required: false },
            { label: 'عنصر تواصل اضافي', name: 'item5', required: false },
            { label: 'Location', name: 'location_en', required: true },
            { label: 'Additional Contact Info', name: 'item4_en', required: false },
            { label: 'Additional Contact Inof', name: 'item5_en', required: false },
            { label: 'فيسبوك', name: 'facebook', required: false },
            { label: 'انستاغرام', name: 'instagram', required: false },
            { label: 'تويتر', name: 'twitter', required: false },
            { label: 'لينكدين', name: 'linkedin', required: false },
            { label: 'سناب شات', name: 'snapchat', required: false },
          ],
      },
    ],
}
